### PR TITLE
Fix mingw warnings

### LINKED ISSUE #66: Signed/Unsigned comparison warnings
When compiling with Mingw, the following warnings appear:
```
OPUNetTransportLayer.cpp: In member function ‘virtual int OPUNetTransportLayer::Receive(OP2Internal::Packet&)’:
OPUNetTransportLayer.cpp:652:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (numBytes == -1)
       ~~~~~~~~~^~~~~
OPUNetTransportLayer.cpp:657:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if (numBytes == -1) {
        ~~~~~~~~~^~~~~
OPUNetTransportLayer.cpp: In member function ‘int OPUNetTransportLayer::ReadSocket(SOCKET, OP2Internal::Packet&, sockaddr_in&)’:
OPUNetTransportLayer.cpp:963:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (numBytes == SOCKET_ERROR) {
               ^
```

### PR DESCRIPTION
**Pull request by Brett208**
Closes #66

@DanRStevens, could you check my work closely. I have never used reinterpret_cast or the win32 functions associated with the changes.

I was able to create a game lobby and have another instance of Outpost 2 join it on my computer. The level didn't start properly, although I don't know if that is because I was using NetFixClient on my CPU with two instances of Outpost 2 or not. 

-Brett

### CODE REVIEW

**Comment by Brett208** [comment]
Tested this a bit more. When trying to start a game, I get the following messages:

Sending Players list to all players

Then a while later I get:

Replicating players list failed

This occurs on this branch and on the master, so if this is not expected behaviour, it isn't being caused by this branch. Not sure if I should be able to use NetFixClient to start a mission with 2 instances on the same computer.

File: OPUNetTransportLayer.cpp [hunk 1]
```diff
@@ -945,27 +945,27 @@ int OPUNetTransportLayer::ReadSocket(SOCKET sourceSocket, Packet& packet, sockad
 	}
 
 	// Check the server port for data
-	unsigned long numBytes;
-	int errorCode = ioctlsocket(sourceSocket, FIONREAD, &numBytes);
-	// Check for success
+	unsigned long byteCountUnsigned; //ioctlsocket sets argp to number of bytes read when passed FIONREAD
```
Comment (DanRStevens) [inline OPUNetTransportLayer.cpp]: I would drop "Unsigned" from `byteCountUnsigned` as that's just repeating the type.

**Review by DanRStevens — APPROVED** [review]
Changes look good.

The problem you encountered is likely unrelated. That error message is expected when NAT punch through fails. I'm a little surprised it failed in your case. It should be possible to self host two instances of Outpost 2 to test. If you're using the loopback IP (127.0.0.1), or an internal LAN IP (192.168.x.x) it should just work, unless perhaps a firewall has blocked it. If you're using the external WAN IP, it should work unless the router doesn't support hairpinning, or the router NAT configuration gets in the way. More details may help diagnose the cause.

**Comment by DanRStevens** [comment]
I see one warning with the updated code:
```
OPUNetTransportLayer.cpp: In member function ‘virtual int OPUNetTransportLayer::Receive(OP2Internal::Packet&)’:
OPUNetTransportLayer.cpp:669:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (numBytes < sizeof(PacketHeader)) {
       ~~~~~~~~~^~~~~~~~~
```

**Comment by DanRStevens** [comment]
Code now compiles cleanly on Linux.

**Comment by Brett208** [comment]
Thanks for reviewing and pushing the commits.
